"""Row and Column Index Manipulator Algorithm (First Confusion Stage).

The algorithm scrambles the positions of pixels by shuffling image rows and columns
independently according to chaotic sequences generated by the logistic map.
"""

from typing import Tuple
import numpy as np
from .logistic_map import iterate_logistic


def _get_row_col_permutations(H: int, W: int, x0: float, r: float) -> Tuple[np.ndarray, np.ndarray]:
    """Generate row and column permutation vectors using continuous logistic map states."""
    # Generate H states for row permutation and W states for column permutation
    total_states = iterate_logistic(x0, r, H + W)
    row_seq = total_states[:H]
    col_seq = total_states[H:]

    row_perm = np.argsort(row_seq)
    col_perm = np.argsort(col_seq)
    return row_perm, col_perm


def row_column_manipulator(
    image: np.ndarray,
    x0: float = 0.123456789,
    r: float = 3.9999,
) -> np.ndarray:
    """Shuffle rows and columns of an image using logistic map permutations.

    Args:
        image: Input array of shape (H, W) or (H, W, C).
        x0: Initial condition for chaotic generator.
        r: Control parameter for chaotic generator.

    Returns:
        np.ndarray: Scrambled image array of the same shape and dtype.
    """
    H, W = image.shape[:2]
    row_perm, col_perm = _get_row_col_permutations(H, W, x0, r)

    # Reorder rows first, then reorder columns
    shuffled = image[row_perm, ...]
    shuffled = shuffled[:, col_perm, ...]

    return shuffled


def inverse_row_column_manipulator(
    shuffled_image: np.ndarray,
    x0: float = 0.123456789,
    r: float = 3.9999,
) -> np.ndarray:
    """Reconstruct original image from shuffled image by inverting row and column permutations.

    Args:
        shuffled_image: Scrambled array of shape (H, W) or (H, W, C).
        x0: Initial condition used during encryption.
        r: Control parameter used during encryption.

    Returns:
        np.ndarray: Restored image array identical to the original input.
    """
    H, W = shuffled_image.shape[:2]
    row_perm, col_perm = _get_row_col_permutations(H, W, x0, r)

    # Invert permutations
    inv_row_perm = np.argsort(row_perm)
    inv_col_perm = np.argsort(col_perm)

    # Reverse column shuffle first, then row shuffle
    restored = shuffled_image[:, inv_col_perm, ...]
    restored = restored[inv_row_perm, ...]

    return restored
